# Generated by Django 4.2.3 on 2023-08-12 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    replaces = [
        (
            "fill_contacts",
            "0001_squashed_0005_remove_phoneuser_is_auto_generate_and_more",
        )
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("date_create", models.DateField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
            ],
        ),
    ]
