# Generated by Django 4.2.3 on 2023-08-04 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneUsers",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.IntegerField()),
                ("date_create", models.DateField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now=True)),
            ],
        ),
    ]
