# Generated by Django 4.2.3 on 2023-08-06 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "fill_contacts",
            "0001_squashed_0005_remove_phoneuser_is_auto_generate_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phoneuser",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="phoneuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
